export const PASSWORD_NAVBAR_LINK: string = 'a[href="/Passwords"]'
export const HOME_NAVBAR_LINK: string = 'a[href="/Home"]'
export const PASSWORD_INPUT: string = 'input[placeholder="password"]'
export const EMAIL_INPUT: string = 'input[placeholder="email address"]'
export const PWNED_BTN: string = '#searchPwnedPasswords'
export const EMAIL_BTN: string = '#searchPwnage'
export const PWNED_MESSAGE_CONTAINER: string = '.pwnTitle'
export const PWNED_MESSAGE_RESULT: string = '#pwnedPasswordResult'
export const PWNED_EMAIL_RESULT: string = '.pwnTitle'
