name: CI
on:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI - Static analysis and Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: '>=20.12.2'

      - name: Yarn Cache
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: ./.github/bin/ci_install.sh

      - name: Prettier
        run: ./.github/bin/ci_prettier.sh

      - name: Build
        run: ./.github/bin/ci_build.sh
